### PR TITLE
changed deprecated hash function

### PR DESCRIPTION
**Pull request by lullu57**

### CODE REVIEW

**Comment by lullu57** [comment]
Changed deprecated hash function to sha 256

**Comment by lullu57** [comment]
Fixed my syntax error and removed backdoor

**Review by alfrunes — APPROVED** [review]

**Review by larsewi — APPROVED** [review]

**Comment by olehermanse** [comment]
Approved, but please submit another PR so you get points for both issues.

**Comment by alfrunes** [comment]
Superseded by #21 and #23

**Pull request closed without merging**
